refresh_rate: 30 seconds

appenders:
  rolling_file:
    kind: rolling_file
    path: "$ENV{APP_DATA_DIR}/logs/app.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "$ENV{APP_DATA_DIR}/logs/app_{}.log"
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] {m}{n}"

root:
  level: info
  appenders:
    - rolling_file
    - stdout
